### ISSUE TITLE
Hello, I encountered the following problem when running the program, how is the database configured over there？

### ISSUE THREAD

**Issue by hc016036** [ThingsPanel/ThingsPanel-Go#21]
/ThingsPanel-Go-main/initialize/psql/psql.go:34
[error] failed to initialize database, got error failed to connect to `host=127.0.0.1 user=postgres database=ThingsPanel`: failed SASL auth (expected AuthenticationSASLFinal message but received unexpected message)

**Comment by hezhuozhuo** [comment]
You can use the DBeaver Database tools to connect to PostgresQL, create a database, import SQL, and configure back-end database configuration files. You can temporarily ignore the sequential database plug-in and skip SQL execution without affecting the import
