### ISSUE TITLE
这些地方为什么不用单例呢？

### ISSUE THREAD

**Issue by sllt** [ThingsPanel/ThingsPanel-Go#25]
像这些地方：

https://github.com/ThingsPanel/ThingsPanel-Go/blob/aae1cfbff9c2cc8a6fa57f3f42b64c03d8586be9/controllers/customer.go#L60

https://github.com/ThingsPanel/ThingsPanel-Go/blob/aae1cfbff9c2cc8a6fa57f3f42b64c03d8586be9/controllers/customer.go#L91

https://github.com/ThingsPanel/ThingsPanel-Go/blob/aae1cfbff9c2cc8a6fa57f3f42b64c03d8586be9/controllers/customer.go#L174

提供一种重构思路：

```go
var Customer = new(customerService)

type customerService struct {}

func (c *customerService) Paginate(name string, offset int, pageSize int) ([]models.Customer, int64) {
}

....
```

调用：

```go
service.Customer.Paginate(your params...)

```

**Comment by hezhuozhuo** [comment]
感谢，多租户重构时候会参考您的意见
