### ISSUE TITLE
sql错误

### ISSUE THREAD

**Issue by hhngdcz** [ThingsPanel/ThingsPanel-Go#35]
2023/03/07 13:57:16.467 [I] [psql.go:28]  F:/Desktop/ThingsPanel-Go/services/tp_dict_service.go:31 ERROR: syntax error at or near "and" (SQLSTATE 42601)
[23.694ms] [rows:0] SELECT count(*) FROM "tp_dict" WHERE  and dict_code = 'chart_type'

**Comment by hezhuozhuo** [comment]
谢谢，此问题已修复
