### ISSUE TITLE
token不能为空    

### ISSUE THREAD

**Issue by hhngdcz** [ThingsPanel/ThingsPanel-Go#36]
![uTools_1678174665732](https://user-images.githubusercontent.com/69241941/223356154-0dc4de1e-b0ce-4dbf-b6e9-e7b8490b3926.png)

使用mqttx连接后发送消息后台显示
前台一直显示设备离线

**Comment by hhngdcz** [comment]
![uTools_1678174999079](https://user-images.githubusercontent.com/69241941/223356944-74bf4a89-4acb-4e01-88b3-9bc34fd72d44.png)
![uTools_1678175023804](https://user-images.githubusercontent.com/69241941/223356953-abae2476-a246-4780-a9a8-5086b5b7a659.png)

**Comment by hezhuozhuo** [comment]
mqtt服务需要用ThingsPanel组织里的gmqtt库，做过二次开发
