### ISSUE TITLE
在device.go中的GetProtocolForm函数中如果ProtocolType是官方TCP也就是ProtocolType=tcp的话会报错，原因就是len（ProtocolType）<4

### ISSUE THREAD

**Issue by hhngdcz** [ThingsPanel/ThingsPanel-Go#92]
![uTools_1680243521703](https://user-images.githubusercontent.com/69241941/229039111-9e78e1e1-dc62-4abf-ac0b-8f20d0865425.png)
![uTools_1680243871008](https://user-images.githubusercontent.com/69241941/229040140-4b82868b-cbe7-41dc-9d0a-05dba3a6c02a.png)

**Comment by hezhuozhuo** [comment]
谢谢，此问题已修复
